---
- name: Add map file(s) to auto.master template
  tags:
    - autofs
  template:
     src: auto.master.d.j2
     dest: "/etc/auto.master.d/{{item.name}}.autofs"
     mode: 0644
  with_items:
    - "{{autofs_indirect_maps}}"
  notify:
    - Restart autofs

- name: Create indirect map files for indirect maps that specify mounts
  tags:
    - autofs
  template:
     src: indirect.j2
     dest: "/etc/{{ item.name }}"
     mode: 0644
  with_items:
    - "{{autofs_indirect_maps}}"
  when: item.mounts is defined and item.name in enabled_autofs_indirect_maps
  notify: Restart autofs

- name: Check map paths
  tags:
    - autofs
  file:
      path: "{{ item.path }}"
      state: directory
  with_items:
    - "{{autofs_indirect_maps}}"
  when: item.name in enabled_autofs_indirect_maps
  notify: Restart autofs
