---
- name: Install AutoFS and dependencies
  tags:
    - configuration
    - autofs
  yum: 
    name: '{{item}}' 
    state: present
  with_items: 
    - "{{autofs_pkgs}}"
  notify:
    - Restart autofs

- name: Enable AutoFS and dependencies for RHEL 7
  tags:
    - configuration
    - autofs
    - nfs
  service: 
    name: "{{item}}" 
    enabled: yes 
    state: started
  with_items:
    - nfs-secure
    - autofs
  when: ansible_distribution_major_version == '7'

- name: Enable AutoFS and dependencies for RHEL 6
  tags:
    - configuration
    - autofs
    - nfs
  service: 
    name: "{{item}}" 
    enabled: yes 
    state: started
  with_items:
    - rpcgssd
    - autofs
  when: ansible_distribution_major_version == '6'

