---
- name: AUTOFS | Include OS-specific variables.
  include_vars: "{{item}}"
  with_first_found:
    - "{{ansible_distribution}}_{{ansible_distribution_major_version}}_{{ansible_distribution_minor_version}}.yml"
    - "{{ansible_distribution}}_{{ansible_distribution_major_version}}.yml"
    - "{{ansible_distribution}}.yml"
    - "{{ansible_os_family}}_{{ansible_distribution_major_version}}_{{ansible_distribution_minor_version}}.yml"
    - "{{ansible_os_family}}_{{ansible_distribution_major_version}}.yml"
    - "{{ansible_os_family}}.yml"
    - default.yml

- include: install.yml

- include: indirect.yml
  when: autofs_indirect_maps is defined
