---
# handlers file for systemd-mounts
# systemd uses - for dir separator, so dirs with dashes need escaped according to systemd-escape rules

#*
#* ## Handlers
#*
#* *Reload systemd* handles reloading the systemd daemon (with daemon_reload)
#* after mounts are established on the system. This should run after any mount
#* is added to, or removed from, the system.
#*
#* The *Enable systemd mount* and *Start systemd mount* handlers are run on any
#* mount that does not have the 'automount' directive set to false, or not set.
#* Alternatively, the *Start systemd automount* and *Enable systemd automount*
#* handlers are run on mounts that have the 'automount' directive set to true.
#*
#* **NOTE**: systemd uses a dash ('-') as a directory separator. Directories
#* that incldue dashes in their path need to be escaped according to the
#* systemd-escape rules (man systemd-escape).
#*

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd_mounts_manage_service

- name: Start systemd mount
  systemd:
    name: "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', \"-\") }}.mount"
    state: started
  with_dict: "{{ systemd_mounts }}"
  when: systemd_mounts_manage_service

- name: Start systemd automount
  systemd:
    name: "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', \"-\") }}.automount"
    state: started
  with_dict: "{{ systemd_mounts }}"
  when: systemd_mounts_manage_service

- name: Enable systemd mount
  systemd:
    name: "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', \"-\") }}.mount"
    enabled: yes
  with_dict: "{{ systemd_mounts }}"
  notify:
    - Start systemd mount
  when: item.value.automount == false

- name: Enable systemd automount
  systemd:
    name: "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', \"-\") }}.automount"
    enabled: yes
  with_dict: "{{ systemd_mounts }}"
  notify:
    - Start systemd automount
  when: item.value.automount == true

- name: Reload autofs
  systemd:
    name: autofs
    state: reloaded
  when: autofs_mounts_manage_service

- name: Restart autofs
  systemd:
    name: autofs
    state: restarted
  when: autofs_mounts_manage_service
