---
- name: Restart autofs
  tags:
    - services
    - automount
  service:
    name: autofs
    state: restarted

- name: Reload systemctl
  tags:
    - services
    - automount
  shell: systemctl daemon-reload && mount -a
