---
# handlers file for systemd-mounts
# systemd uses - for dir separator, so dirs with dashes need escaped according to systemd-escape rules

#==============================================================================
# Flowchart:
#   - Reload systemd handler: This should be the first handler called anytime we
#      add/remove a unit file for [auto]mount.
#   - Enable systemd [auto]mount:
#       1. Run systemctl enable [unit-file]
#       2. Run systemctl start [unit-file]
# 
#==============================================================================

- name: Reload systemd
  systemd:
    daemon_reload: yes
  when: systemd_mounts_manage_service

- name: Start systemd mount
  command: systemctl start "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', "-") }}.mount"
  with_dict: "{{ systemd_mounts }}"
  when: systemd_mounts_manage_service

- name: Start systemd automount
  command: systemctl start "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', "-") }}.automount"
  with_dict: "{{ systemd_mounts }}"
  when: systemd_mounts_manage_service

- name: Enable systemd mount
  command: systemctl enable "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', "-") }}.mount"
  with_dict: "{{ systemd_mounts }}"
  notify:
    - Start systemd mount
  when: item.value.automount == false

- name: Enable systemd automount
  command: systemctl enable "{{ item.value.mount[1:] | replace('-', '\\x2d') | replace('/', "-") }}.automount"
  with_dict: "{{ systemd_mounts }}"
  notify:
    - Start systemd automount
  when: item.value.automount == true

- name: Reload autofs
  systemd:
    name: autofs
    state: reloaded
  when: autofs_mounts_manage_service

- name: Restart autofs
  systemd:
    name: autofs
    state: restarted
  when: autofs_mounts_manage_service
